In [1]:
import pandas as pd
import numpy as np

In [3]:
nums = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
nums

0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64

In [4]:
temp = np.diff(np.sign(np.diff(nums)))
temp

array([-2,  0,  2, -2,  0,  2,  0, -2])

In [5]:
np.diff(nums)

array([ 7, -1, -2,  1, -1, -2,  1,  3, -6])

In [7]:
result = np.where(temp == -2)[0] + 1
result

array([1, 4, 8])